language: python
python:
  - 3.7

env:
  - DJANGO=2.0.10

addons:
  postgresql: "9.4"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
services:
  - postgresql

install:
  - pip install -r retrieverdash/requirements.txt
script:
  - python setup.py install
  - retriever ls
  - pytest -v
  - python retrieverdash/manage.py test core.tests -v 2
before_script:
  - sqlite3 --version
  - psql -c 'create database testdb;' -U postgres
